### ISSUE TITLE
ssh_public_key is not working with .pem file

### ISSUE THREAD

**Issue by StalinBabuG** [scholzj/terraform-aws-minikube#7]
Hi 

Thanks for sharing the module. 
I am using the .pem file on my windows desktop for the below parameter, but it is not working.  

ssh_public_key = "~/my-minikube.pem"

Is it right approach to use this module or any other way, can you please share the details. 

Thank you

**Comment by scholzj** [comment]
I do not have any Windows machine. So I have no idea how things work on Windows. The SSH public key is normally not in a PEM format but a it is in an SSH format. E.g.:
```
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAklOUpkDHrfHY17SbrmTIpNLTGK9Tjom/BWDSU
GPl+nafzlHDTYW7hdI4yZ5ew18JH4JW9jbhUFrviQzM7xlELEVf4h9lFX5QVkbPppSwg0cda3
Pbv7kOdJ/MTyBlWXFCR+HAo3FXRitBqxiX1nKhXpHAZsMciLq8V6RjsNAQwdsdMFvSlVK/7XA
t3FaoJoAsncM1Q9x5+3V0Ww68/eIFmb1zuUFljQJKprrX88XypNDvjYNby6vw/Pb0rwert/En
mZ+AW4OZPnTPI89ZPmVMLuayrD2cE86Z/il8b+gw3r3+1nKatmIkjn2so1d01QraTlMqVSsbx
NrRFi9wrf+M7Q== schacon@mylaptop.local
```

So you should make sure your file looks like this.

**Comment by StalinBabuG** [comment]
Thank you for the reply! 

Do you use Linux desktop to connect AWS Infra or any Linux Jump server in AWS. 
 
Will the module take the below parameter or should I use hosted zone as public. 
hosted_zone_private = true 

Can you please share the details. 
Thanks in advance!

**Comment by scholzj** [comment]
I normally use local MacOS and public DNS zone. The private zone is an option if you don't have any public zone, you should be then able to access it through the node IP address for example even through the zone is private. Or through the private DNS but then you probably need to be inside your AWS VPC.

**Comment by StalinBabuG** [comment]
Now its clear.  

Thank you so much for the support.

**Comment by StalinBabuG** [comment]
It's working fine from Windows too. Thanks for the support!

**Comment by StalinBabuG** [comment]
Closing the issue.
