### ISSUE TITLE
Requires a EULA Agreement

### ISSUE THREAD

**Issue by sarasensible** [scholzj/terraform-aws-minikube#8]
Running this module I get the following:

```
Error: creating EC2 Instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=cvugziknvmxgqna9noibqnnsy
│ 	status code: 401, request id: 6784aa53-790a-470c-b3a8-28ebd23a433c
│
│   with module.minikube.aws_instance.minikube,
│   on .terraform/modules/minikube/main.tf line 155, in resource "aws_instance" "minikube":
│  155: resource "aws_instance" "minikube" {
```

Is there any alternative supported image that does not require agreeing to a EULA?

**Comment by scholzj** [comment]
And what imaged did you configured to be used? Or do you use just the default one? TBH, I do not remember if I ever did any EULA. It uses the regular CentOS image by default. So if it needs something, it is probably some AWS requirement.

**Comment by sarasensible** [comment]
@scholzj  thank you so much for the quick response!  I used the default one, it seems it is an AWS requirement.  It can be viewed at https://aws.amazon.com/marketplace/server/procurement?productId=d9a3032a-921c-4c6d-b150-bde168105e42 .  The EULA reads:

```
CentOS-7 EULA

CentOS-7 comes with no guarantees or warranties of any sorts,
either written or implied.

The Distribution is released as GPLv2. Individual packages in the
distribution come with their own licences.
```

This is acceptable for our use which is dev testing.  It is probably enough to give users a heads up that this is required nowadays.  Thanks again!
